Repository AY2122S1-CS2103T-T15-2/tp, pull requests merged in 2021-10, with the labels that each got.

#101 Implement task
  .gitignore
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskListManager.java
  src/main/java/seedu/address/model/member/Member.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMember.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/data/JsonSerializableAddressBookTest/duplicateMemberAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalMembersAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/PAddCommandTest.java
  src/test/java/seedu/address/model/member/MemberTest.java
  src/test/java/seedu/address/model/task/TaskListTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMemberTest.java
  src/test/java/seedu/address/testutil/MemberBuilder.java
  src/test/java/seedu/address/testutil/TaskListBuilder.java
  src/test/java/seedu/address/testutil/TypicalMembers.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High, type.Enhancement

#117 Fix javadocs
  build.gradle
  src/main/java/seedu/address/ui/EventCard.java
Labels: priority.High, type.Documentation

#130 implement tlist command with tests
  src/main/java/seedu/address/logic/commands/TaddCommand.java
  src/main/java/seedu/address/logic/commands/TlistCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TlistCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/TlistCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/TlistCommandParserTest.java
Labels: priority.High, type.Enhancement

#131 DG for UI.
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.High, type.Documentation

#233 Fix GUI, documentations and minor command bug
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/event/EaddCommand.java
  src/main/java/seedu/address/logic/commands/event/EeditCommand.java
  src/main/java/seedu/address/logic/commands/event/EfindCommand.java
  src/main/java/seedu/address/logic/commands/member/MaddCommand.java
  src/main/java/seedu/address/logic/commands/member/MeditCommand.java
  src/main/java/seedu/address/logic/commands/member/MfindCommand.java
  src/main/java/seedu/address/logic/commands/member/MlistCommand.java
  src/main/java/seedu/address/logic/commands/member/MtfindCommand.java
  src/main/java/seedu/address/logic/commands/member/PfindCommand.java
  src/main/java/seedu/address/logic/commands/task/TdoneCommand.java
  src/main/java/seedu/address/logic/commands/task/TeditCommand.java
  src/main/java/seedu/address/logic/parser/member/MeditCommandParser.java
  src/main/java/seedu/address/logic/parser/member/MlistCommandParser.java
  src/main/java/seedu/address/model/module/event/Event.java
  src/main/java/seedu/address/model/module/member/position/Position.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MemberCard.java
  src/main/java/seedu/address/ui/MemberListPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MemberListCard.fxml
  src/main/resources/view/MemberListPanel.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MeditCommandParserTest.java
Labels: priority.Medium, type.Task, type.Documentation, hacktoberfest-accepted
