Repository AY2122S1-CS2103T-T15-2/tp, pull requests merged in 2021-11, with the labels that each got.

#236 Fix tdone, tundone and change task to be unique
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/task/TaddCommand.java
  src/main/java/seedu/address/logic/commands/task/TdoneCommand.java
  src/main/java/seedu/address/logic/commands/task/TeditCommand.java
  src/main/java/seedu/address/logic/commands/task/TundoneCommand.java
  src/main/java/seedu/address/model/module/task/Task.java
  src/main/java/seedu/address/model/module/task/TaskList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/task/TaddCommandTest.java
  src/test/java/seedu/address/model/module/task/TaskListTest.java
  src/test/java/seedu/address/model/module/task/TaskTest.java
Labels: priority.High, type.Bug

#239 Make name case-insensitive when checking for equality.
  src/main/java/seedu/address/model/module/Name.java
  src/test/java/seedu/address/model/module/member/MemberTest.java
Labels: type.Bug, severity.Medium, hacktoberfest-accepted

#243 fix eedit PED errors by changing implementation. Add some parts of th…
  docs/team/samuel-bit-prog.md
  src/main/java/seedu/address/logic/commands/event/EeditCommand.java
  src/main/java/seedu/address/logic/parser/event/EeditCommandParser.java
Labels: priority.High, type.Bug, type.Documentation

#242 fix tadd bug
  docs/team/liuzhi1an.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/event/EaddCommand.java
  src/main/java/seedu/address/logic/commands/task/TaddCommand.java
  src/main/java/seedu/address/logic/commands/task/TdelCommand.java
  src/main/java/seedu/address/logic/commands/task/TeditCommand.java
  src/main/java/seedu/address/logic/commands/task/TundoneCommand.java
  src/main/java/seedu/address/model/module/Name.java
  src/main/java/seedu/address/model/module/event/EventDate.java
  src/main/java/seedu/address/model/module/task/TaskDeadline.java
  src/test/java/seedu/address/logic/commands/task/TaddCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TdelCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TlistCommandTest.java
Labels: priority.High, type.Bug

#244 Add tests for Name class, draft PPP.
  docs/team/gwphua.md
  src/test/java/seedu/address/model/module/NameTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium, hacktoberfest-accepted

#251 Fix date issue
  docs/UserGuide.md
  docs/team/tsiyuk.md
  src/main/java/seedu/address/commons/core/index/Index.java
Labels: priority.High, type.Bug

#254 Fix bug: deleting wrong task after tlist
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/task/TdelCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/member/MaddCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TaddCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TdelCommandTest.java
Labels: priority.High, type.Bug

#264 modify UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#261 Small Changes to Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/UndoRedoState5.png
Labels: priority.Medium, type.Documentation

#267 Fix task list refreshing after tadd
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High, type.Bug

#270 Add tadd and tdone in DG
  docs/DeveloperGuide.md
  docs/diagrams/task/TaskAddExecutionSequenceDiagram.puml
  docs/diagrams/task/TaskAddSequenceDiagram.puml
  docs/diagrams/task/TaskDoneSequenceDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/task/TaskAddExecutionSequenceDiagram.png
  docs/images/task/TaskAddSequenceDiagram.png
  docs/images/task/TaskDoneSequenceDiagram.png
Labels: priority.High, type.Documentation

#256 Add in EeditParser / EeditCommand tests.
  docs/team/gwphua.md
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/member/MdelCommandTest.java
  src/test/java/seedu/address/logic/commands/member/MeditCommandTest.java
  src/test/java/seedu/address/logic/commands/member/MlistCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TlistCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EeditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MdelCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MeditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/testutil/EditEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Enhancement, priority.Medium

#274 Test Dates
  src/test/java/seedu/address/model/module/event/EventDateTest.java
  src/test/java/seedu/address/model/module/task/TaskDeadlineTest.java
Labels: type.Enhancement, priority.Medium

#275 add task testcases and update PPP
  docs/team/liuzhi1an.md
  src/main/java/seedu/address/logic/commands/task/TeditCommand.java
  src/main/java/seedu/address/logic/commands/task/TfindCommand.java
  src/main/java/seedu/address/logic/commands/task/TlistCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/task/TdoneCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TeditCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TfindCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TundoneCommandTest.java
  src/test/java/seedu/address/logic/parser/TaddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TdoneCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TeditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TfindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TundoneCommandParserTest.java
Labels: priority.High, type.Enhancement

#276 Add model design and workflow in DG
  docs/DeveloperGuide.md
  docs/diagrams/AlternativeModelClassDiagram.puml
  docs/diagrams/CommandActivityDiagram.puml
  docs/diagrams/task/TaskAddSequenceDiagram.puml
  docs/images/AlternativeModelClassDiagram.png
  docs/images/CommandActivityDiagram.png
  docs/images/ER.png
Labels: priority.High, type.Documentation

#278 Add maunal testing guide for task
  docs/DeveloperGuide.md
  docs/diagrams/task/TaskAddExecutionSequenceDiagram.puml
  docs/diagrams/task/TaskAddSequenceDiagram.puml
  docs/diagrams/task/TaskDoneSequenceDiagram.puml
  docs/images/task/TaskAddExecutionSequenceDiagram.png
  docs/images/task/TaskAddSequenceDiagram.png
  docs/images/task/TaskDoneSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/task/TaddCommandParser.java
Labels: priority.High, type.Documentation

#277 add task testcases for event parsers
  src/main/java/seedu/address/logic/commands/task/TeditCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/event/EaddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EdelCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EeditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EfindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EmaddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EmarkAllCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EmarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EmdelCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EunmarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/member/MaddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/member/MdelCommandParserTest.java
  src/test/java/seedu/address/logic/parser/member/MeditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/member/MfindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TaddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TdelCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TlistCommandParserTest.java
Labels: priority.High, type.Enhancement

#279 Samuel dg
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/member/PfindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/member/PfindCommandParser.java
  unused/PfindCommand.java
  unused/PfindCommandParser.java
Labels: priority.High, type.Documentation

#280 Fix bugs, refactor DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EmaddExecutionSequenceDiagram.puml
  docs/diagrams/EmaddSequenceDiagram.puml
  docs/diagrams/MdelSequenceDiagram.puml
  docs/diagrams/MlistExecutionSequenceDiagram.puml
  docs/diagrams/MlistSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/EmaddExecutionSequenceDiagram.png
  docs/images/EmaddSequenceDiagram.png
  docs/images/MdelSequenceDiagram.png
  docs/images/MlistExecutionSequenceDiagram.png
  docs/images/MlistSequenceDiagram.png
  docs/images/UImockup.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState4.png
  docs/images/modeloverview.png
  docs/images/modelv1.png
  docs/images/modelv2.png
  src/main/java/seedu/address/logic/commands/event/EaddCommand.java
  src/main/java/seedu/address/logic/commands/event/EdelCommand.java
  src/main/java/seedu/address/logic/commands/event/EeditCommand.java
  src/main/java/seedu/address/logic/commands/event/EfindCommand.java
  src/main/java/seedu/address/logic/commands/event/EmaddCommand.java
  src/main/java/seedu/address/logic/commands/event/EmarkAllCommand.java
  src/main/java/seedu/address/logic/commands/event/EmarkCommand.java
  src/main/java/seedu/address/logic/commands/event/EmdelCommand.java
  src/main/java/seedu/address/logic/commands/event/EunmarkCommand.java
  src/main/java/seedu/address/logic/commands/member/MfindCommand.java
  src/main/java/seedu/address/logic/commands/member/MlistCommand.java
  src/main/java/seedu/address/logic/commands/member/MtfindCommand.java
  src/main/java/seedu/address/logic/commands/task/TaddCommand.java
  src/main/java/seedu/address/logic/commands/task/TdelCommand.java
  src/main/java/seedu/address/logic/commands/task/TdoneCommand.java
  src/main/java/seedu/address/logic/commands/task/TeditCommand.java
  src/main/java/seedu/address/logic/commands/task/TfindCommand.java
  src/main/java/seedu/address/logic/commands/task/TlistCommand.java
  src/main/java/seedu/address/logic/commands/task/TundoneCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/module/event/Event.java
  src/main/java/seedu/address/model/module/member/Member.java
  src/test/java/seedu/address/model/module/member/MemberTest.java
Labels: priority.High, type.Task, type.Bug, type.Documentation

#281 Update PPP for final submission.
  docs/team/gwphua.md
Labels: priority.Medium, type.Documentation

#283 Update PPP, add more manual test cases and clean up some code
  docs/DeveloperGuide.md
  docs/team/tsiyuk.md
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/task/TeditCommandParser.java
  src/main/java/seedu/address/model/module/task/Task.java
  src/main/java/seedu/address/model/module/task/TaskList.java
Labels: priority.Medium, type.Documentation

#284 add missing diagram
  docs/images/EventAddExecutionSequenceDiagram.png
Labels: type.Documentation

#285 Update Developer guide, User Guide and images
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/CommandActivityDiagram.puml
  docs/diagrams/EmaddExecutionSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/MlistExecutionSequenceDiagram.puml
  docs/images/CommandActivityDiagram.png
  docs/images/EmaddExecutionSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/MlistExecutionSequenceDiagram.png
  docs/images/ailurusLogo.png
  docs/images/event/EmaddExecutionSequenceDiagram.png
  docs/images/event/EmaddSequenceDiagram.png
  docs/images/event/EventAddExecutionSequenceDiagram.png
  docs/images/event/EventAddSequenceDiagram.png
  docs/images/event/EventMarkExecutionSequenceDiagram.png
  docs/images/event/EventMarkSequenceDiagram.png
  docs/images/member/MdelSequenceDiagram.png
  docs/images/member/MlistExecutionSequenceDiagram.png
  docs/images/member/MlistSequenceDiagram.png
Labels: type.Documentation

#286 Clean up code
  docs/DeveloperGuide.md
  docs/team/tsiyuk.md
  src/main/java/seedu/address/logic/commands/task/TaddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/TaskUtil.java
Labels: priority.Medium, type.Documentation

#287 Changes along DG proof-reading.
  docs/DeveloperGuide.md
Labels: priority.High, severity.Medium, type.Documentation

#289 Update PPP and fix minor doc bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UndoRedoState1.puml
  docs/images/UndoRedoState1.png
  docs/team/leeroy999.md
Labels: type.Documentation

#288 add ppp and test for event
  docs/team/samuel-bit-prog.md
  src/test/java/seedu/address/model/module/event/EventTest.java
Labels: priority.High, type.Documentation
